### ISSUE TITLE
About internship

### ISSUE THREAD

**Issue by txytju** [Michel-liu/GroupPose#1]
Hi Huan Liu, I'm Xingye Tian from Ytech AI lab, Kuaishou. I'm creating this issue to ask that whether you are interested in internship in our lab working on body pose/ hand pose estimation. Our team focus on perception of human and the environment, espicially motion capture and digital human. Interns here mainly works on cutting-edge tech and solve problems that are both important for research and industry. If you are interested or have any questions, please contact me, wechat txy13512216389.

**Comment by Michel-liu** [comment]
Thanks for your interest in our work. I will contact you later and apologize for any inconvenience by closing this issue.
