### ISSUE TITLE
the version of cuda that comes with the driver

### ISSUE THREAD

**Issue by rrenle** [Michel-liu/GroupPose#12]
Hi, the version of cuda toolkit in the conda environment is 11.0, then, what is the version of cuda that comes with the driver? Because my model reproduction results of Resnet is not consistent with yours. While compiling CUDA operators, the cuda that comes with the driver will be used, so I want to know if that's what's causing it.

**Comment by Kelatte** [comment]
in models/grouppose/ops/make.sh, I found cuda11.1. Maybe the author is using cuda11.1.

**Comment by rrenle** [comment]
@Kelatte While compiling CUDA operators, the "python setup.py build install" is used, make.sh is not called. So It's not sure.

**Comment by Michel-liu** [comment]
Thank you for your interest in our work. The CUDA version is 11.0. A higher version like 11.1 may work too, while you need to update the PyTorch for matching.

**Comment by Iterfqly** [comment]
> Hi, the version of cuda toolkit in the conda environment is 11.0, then, what is the version of cuda that comes with the driver? Because my model reproduction results of Resnet is not consistent with yours. While compiling CUDA operators, the cuda that comes with the driver will be used, so I want to know if that's what's causing it.

thanks for your reply, I will close the issue.

**Comment by rrenle** [comment]
> Thank you for your interest in our work. The CUDA version is 11.0. A higher version like 11.1 may work too, while you need to update the PyTorch for matching.

thanks for your reply, I will close the issue.
