### ISSUE TITLE
Batch-size per GPU

### ISSUE THREAD

**Issue by matteo-fincato** [Michel-liu/GroupPose#13]
Hi everyone,

I have a question regarding implementation details. Are you using a batch size of 16 per GPU, along with 8 GPUs per epoch? Or are you using a batch-size of 2 per GPUs with 8GPUs to achieve 16 batch-size for every epoch?

Thanks

**Comment by Michel-liu** [comment]
Hi~ The total batch size is 16, with 2 images on each GPU.
