### ISSUE TITLE
Question about the reported metrics of Poseur in your paper

### ISSUE THREAD

**Issue by Kelly510** [Michel-liu/GroupPose#14]
Hi. I have a question about the reported metrics of Poseur in your paper. 
In the original Poseur paper, AP is 75.4 with ResNet-50 backbone. However, it is 74.2 in your paper with the same backbone. May I ask the reason of this difference? 

<img width="400" alt="微信图片_20231220143706" src="https://github.com/Michel-liu/GroupPose/assets/49122590/1d95f57f-a99f-4302-903c-3b07e23777f9">

<img width="400" alt="微信图片_20231220143535" src="https://github.com/Michel-liu/GroupPose/assets/49122590/aa7639d2-0e58-4882-855c-b6a49e5060d6">

**Comment by Michel-liu** [comment]
Hi~ The result of Poseur comes from EDPose (https://arxiv.org/pdf/2302.01593.pdf), you can refer to Table 3.
