### ISSUE TITLE
the size of refpoint_pose is 36 not 34

### ISSUE THREAD

**Issue by WEIZHIHONG720** [Michel-liu/GroupPose#4]
hi, thanks for your good job!  In the groupose.py, the size of refpoint_pose is 36 not 34 ? What does the extra 2 on the front do?
<img width="874" alt="image" src="https://github.com/Michel-liu/GroupPose/assets/43931281/08fa1dd0-4399-44e6-8c00-04f6a85f2175">

**Comment by Michel-liu** [comment]
Thanks for your interest in our work. It's the reference point for the instance query during cross-attention (see Section 3.2 in our paper).
The code lines here (https://github.com/Michel-liu/GroupPose/blob/127fe0e2e7b54d7a43420015a2e90e456a8ea1fb/models/grouppose/transformer.py#L305C13-L307C111) may help you.

**Comment by WEIZHIHONG720** [comment]
> Thanks for your interest in our work. It's the reference point for the instance query during cross-attention (see Section 3.2 in our paper). The code lines here (https://github.com/Michel-liu/GroupPose/blob/127fe0e2e7b54d7a43420015a2e90e456a8ea1fb/models/grouppose/transformer.py#L305C13-L307C111) may help you.

thanks, i know
