### ISSUE TITLE
half_pose_ref_point_head

### ISSUE THREAD

**Issue by WEIZHIHONG720** [Michel-liu/GroupPose#5]
Thanks for your works ! In the code of decoder, what is the purpose of  half_pose_ref_point_head ? Looking forward to your reply。
<img width="1061" alt="image" src="https://github.com/Michel-liu/GroupPose/assets/43931281/2fa83cb3-0edc-4101-8b2f-892a0845daf5">

**Comment by Michel-liu** [comment]
The head is used to encode the position of each query.

**Comment by WEIZHIHONG720** [comment]
> The head is used to encode the position of each query.

Why do you need a new head to encode the position after gen_sineembed_for_position() ?

**Comment by Michel-liu** [comment]
Sorry for the delayed reply. I've been very busy lately. For more information about this setting, I recommend more DETR-related literature.
